runtime: nodejs16 # or another supported version
service: be-pajakkendaraan-login

env_variables:
  BUCKET_NAME: "be-vehicletaxes-bucket"
  SECRET_KEY: "vehicletaxes"
  DATABASE_URL: "mysql://root@34.68.240.215:3306/vehicletaxes?schema=public"
